# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dude, Where's My Podcast?
email: tylerwchilds@gmail.com
description: >
  The Dude, Where's My Podcast? Podcast is a pop-culture blog
  that was founded in 2005 or 2006. We really don't remember.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dwmpp.tylerchilds.com" # the base hostname & protocol for your site
paginate: 4

# Build settings
markdown: kramdown
permalink: pretty

# Jekyll plugins
gems:
- jekyll-mentions
- jekyll-redirect-from

jekyll-mentions: https://twitter.com
